import { useEffect, useState } from "react";
import { ArrowLeft, MessageSquare, Lightbulb, ChevronDown, ChevronUp} from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { interviewService } from "../../services/interviewService"; 
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import { getScoreStyles } from '@/utils/helpers';
import LoadingSpinner from "@/components/common/LoadingSpinner";
import { Button } from "@/components/ui/button";
export default function InterviewResult() {
  const navigate = useNavigate();
  const { sessionId } = useParams();
  const [loading, setLoading] = useState(true);
  const [resultData, setResultData] = useState(null);
  const [error, setError] = useState(null);
  const [expandedQuestionId, setExpandedQuestionId] = useState(null);

 useEffect(() => {
  const fetchResult = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await interviewService.getInterviewById(sessionId);
      console.log("Real Backend Response:", response);

      if (!response) {
        throw new Error("No data received from server");
      }
      const session = response?.session || {};
      const questionsList = response?.questions || [];
      const scoreVal = session.overall_score ?? 0;
      const scoreStyles = getScoreStyles(scoreVal);
      const createdAt = new Date(session.createdAt || response.createdAt);
      const endTime = new Date(
        session.completed_at || session.updatedAt || response.completed_at || new Date()
      );

      const durationMinutes = Math.round(
        (endTime - createdAt) / (1000 * 60)
      );
      const formattedData = {
        score: scoreVal,
        scoreStroke: scoreStyles.stroke, 
        scoreBadgeClass: scoreStyles.badge,
        jobTitle: session.jobTitle || "Job Role",
        
        status: session.hiringRecommendation || "Completed",
        date: new Date(session.completed_at || session.createdAt || new Date()).toLocaleDateString("en-US", {
          month: "short", day: "numeric", year: "numeric"
        }),
        duration: `${durationMinutes} min`,
        overallFeedback: session.overall_feedback || "No general feedback generated by AI yet.",
        tips: Array.isArray(session.tips_for_improvement) 
          ? session.tips_for_improvement 
          : (session.tips_for_improvement ? [session.tips_for_improvement] : []),
        
        questionsBreakdown: (questionsList || []).map((q, idx) => {
          const scoreVal = q.score ?? q.question_score ?? 0;
          return {
            id: q.order_index || idx + 1,
            text: q.question_text || "Question Text",
            scoreNum: scoreVal,
            scoreStr: `${scoreVal}/10`,
            userAnswer: q.user_answer || "No answer recorded.",
            aiFeedback: q.ai_feedback || q.feedback || "No specific feedback available."
          };
        })
      };

      setResultData(formattedData);
    } catch (err) {
      console.error("Fetch result error:", err);
      setError(err?.response?.data?.message || err.message || "Failed to load results.");
    } finally {
      setLoading(false);
    }
  };

  if (sessionId) {
    fetchResult();
  }
}, [sessionId]);
  const toggleQuestion = (id) => {
    setExpandedQuestionId(expandedQuestionId === id ? null : id);
  };

  if (loading) {
    return (
      <LoadingSpinner/>
    );
  }

  if (error) {
    return (
      <div className="text-center p-12  min-h-[80lvh] flex flex-col items-center justify-center gap-4">
        <p className="text-status-error font-bold text-lg">Error: {error}</p>
        <Button onClick={() => navigate("/interview")} className=" font-semibold hover:bg-primary/90 cursor-pointer p-5 text-sm">
          Go Back to Sessions
        </Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background text-foreground antialiased font-sans px-4 py-8 md:px-12 w-full">
      <div className="w-full max-w-4xl mx-auto space-y-6">
        <div className="flex items-center">
          <button onClick={() => navigate("/interview")} className="flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft size={16} /> Back to sessions
          </button>
        </div>

        <div className="bg-card border border-border rounded-xl p-6 flex flex-col sm:flex-row items-center gap-6 shadow-xs text-card-foreground">
          
          {/* Progress Bar */}
          <div className="mx-auto w-28 h-28 sm:w-32 sm:h-32 flex flex-col items-center justify-center shrink-0 sm:mx-0">
            <div className="relative w-full h-full">
              <CircularProgressbar
                value={resultData.score}
                strokeWidth={9}
                styles={buildStyles({
                  trailColor: 'var(--muted)',
                  pathColor: resultData.scoreStroke,
                  pathTransitionDuration: 0.5,
                })}
              />
              <div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center text-center">
                <span className="text-2xl font-bold tracking-tight leading-none text-foreground sm:text-3xl">
                  {resultData.score}%
                </span>
                <span className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold mt-0.5">
                  Score
                </span>
              </div>
            </div>
          </div>

          <div className="flex-1 text-center sm:text-left space-y-2">
            <span className="text-[11px] font-bold text-muted-foreground uppercase tracking-wider block">
              INTERVIEW RESULTS
            </span>
            <h2 className="text-2xl font-bold tracking-tight text-foreground capitalize">
              {resultData.jobTitle}
            </h2>
            
            <div className="flex items-center justify-center sm:justify-start flex-wrap gap-2 text-sm font-medium">
              <span className={`bg-secondary text-secondary-foreground px-2.5 py-0.5 rounded-md  font-semibold text-md border ${resultData.scoreBadgeClass}`}>
                {resultData.status}
              </span>
              <span className="text-muted-foreground font-medium">{resultData.date}</span>
              <span className="text-muted-foreground font-normal">•</span>
              <span className="text-muted-foreground font-medium">{resultData.duration}</span>
            </div>
          </div>
        </div>

        {/* overallFeedback */}
        <div className="bg-card border border-border rounded-xl p-6 shadow-xs w-full space-y-4 text-card-foreground">
          <h3 className="text-md font-bold flex items-center gap-2 tracking-tight text-foreground">
            <MessageSquare size={18} className="text-brand-primary" /> Overall Feedback
          </h3>
          <p className="text-sm font-normal text-muted-foreground leading-relaxed">
            {resultData.overallFeedback}
          </p>

          {/* Tips */}
          {resultData.tips && resultData.tips.length > 0 && (
            <div className="pt-4 border-t border-border space-y-3">
              <h3 className="text-sm font-bold text-status-warning flex items-center gap-1.5 tracking-wider">
                <Lightbulb size={18} className="text-status-warning fill-status-warning/20" /> Tips for Improvement
              </h3>
              <ul className="space-y-2 pl-0.5">
                {resultData.tips.map((tip, idx) => (
                  <li key={idx} className="flex items-start gap-2 text-sm font-normal text-muted-foreground leading-relaxed">
                    <span className="w-1.5 h-1.5 bg-brand-primary rounded-full mt-2 flex-shrink-0" />
                    {tip}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        <div className="bg-card border border-border rounded-xl shadow-xs overflow-hidden w-full text-card-foreground">
          <div className="p-5 border-b border-border bg-card">
            <h3 className="text-base font-bold tracking-tight text-foreground">Questions Breakdown</h3>
            <p className="text-xs font-medium text-muted-foreground mt-0.5">{resultData.questionsBreakdown.length} questions answered</p>
          </div>

          <div className="divide-y divide-border">
            {resultData.questionsBreakdown.map((q) => {
              const isExpanded = expandedQuestionId === q.id;

              return (
                <div key={q.id} className="w-full">
                  <div 
                    onClick={() => toggleQuestion(q.id)}
                    className="p-4 flex items-start justify-between gap-4 hover:bg-muted/50 cursor-pointer select-none transition-colors"
                  >
                    <div className="flex items-start gap-3">
                      <span className="w-7 h-7 bg-secondary text-secondary-foreground font-bold text-sm rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                        {q.id}
                      </span>
                      <p className="text-sm font-medium text-foreground tracking-tight leading-snug">
                        {q.text}
                      </p>
                    </div>
                    
                    <div className="flex items-center gap-2 flex-shrink-0 mt-0.5">
                      <span className={`font-semibold text-sm px-2 py-1 rounded-full border border-status-success/20 text-status-success bg-status-success/10`}>
                        {q.scoreStr}
                      </span>
                      {isExpanded ? <ChevronUp size={16} className="text-muted-foreground" /> : <ChevronDown size={16} className="text-muted-foreground" />}
                    </div>
                  </div>

                  {isExpanded && (
                    <div className="px-12 pb-5 pt-1 bg-muted/50 border-t border-border space-y-4">
                      <div className="bg-card border border-border p-4 rounded-lg shadow-xs mt-2">
                        <span className="text-[11px] font-bold text-muted-foreground tracking-wider uppercase block mb-1">
                          Your Answer
                        </span>
                        <p className="text-sm font-normal text-foreground leading-relaxed">
                          {q.userAnswer}
                        </p>
                      </div>

                      <div className="bg-secondary/60 border border-border p-4 rounded-lg">
                        <span className="text-[11px] font-bold text-secondary-foreground tracking-wider uppercase block mb-1">
                          Feedback
                        </span>
                        <p className="text-sm font-normal text-foreground leading-relaxed">
                          {q.aiFeedback}
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}