import { useEffect, useState } from "react";
import { ArrowLeft, MessageSquare, Lightbulb, ChevronDown, ChevronUp, CheckCircle2, Loader2 } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { interviewService } from "../../services/interviewService"; 

export default function InterviewResult() {
  const navigate = useNavigate();
  const { sessionId } = useParams();
  const [loading, setLoading] = useState(true);
  const [resultData, setResultData] = useState(null);
  const [error, setError] = useState(null);
  const [expandedQuestionId, setExpandedQuestionId] = useState(null);

  useEffect(() => {
    const fetchResult = async () => {
      try {
        setLoading(true);
        setError(null);

        // جلب البيانات الحقيقية من الباكيند
        const response = await interviewService.getInterviewById(sessionId);
        
        // طباعة البيانات في الـ Console لتتأكدي من الـ Structure القادم من السيرفر
        console.log("Real Backend Response Data:", response);

        // بناء البيانات وربطها ديناميكياً بما يرجعه الـ AI والباكيند عندكِ
        const formattedData = {
          score: response?.overall_score || response?.session?.overall_score || 0,
          jobTitle: response?.jobTitle || response?.session?.jobTitle || "Job Role",
          status: response?.hiringRecommendation || response?.session?.hiringRecommendation || "Completed",
          date: new Date(response?.completed_at || response?.createdAt || new Date()).toLocaleDateString("en-US", {
            month: "short", day: "numeric", year: "numeric"
          }),
          duration: response?.duration || response?.session?.duration ? `${response?.duration || response?.session?.duration} min` : "15 min", 
          overallFeedback: response?.overall_feedback || response?.session?.overall_feedback || "No general feedback generated by AI yet.",
          
          // تحويل الـ tips لمصفوفة سواء كانت قادمة كـ Array أو String
          tips: Array.isArray(response?.tips_for_improvement || response?.session?.tips_for_improvement) 
            ? (response?.tips_for_improvement || response?.session?.tips_for_improvement) 
            : (response?.tips_for_improvement || response?.session?.tips_for_improvement ? [response?.tips_for_improvement || response?.session?.tips_for_improvement] : []),
          
          // 💡 الربط الديناميكي الفعلي للأسئلة، إجابة اليوزر، وتقييم الـ AI
          questionsBreakdown: (response?.questions || response?.session?.questions || []).map((q, idx) => ({
            id: q.order_index || idx + 1,
            text: q.question_text || "Question Text",
            // عرض درجة الـ AI لكل سؤال (مثال: 9/10)
            score: q.score ? `${q.score}/10` : `${q.question_score || 0}/10`,
            // 📝 إجابة اليوزر الحقيقية الـ كتبها في الانترفيو
            userAnswer: q.user_answer || q.userAnswer || "No answer recorded for this question.",
            // ✨ كومنت وتقييم الـ AI الحقيقي للسؤال ده بالذات
            aiFeedback: q.ai_feedback || q.aiFeedback || q.feedback || "No specific AI feedback available for this answer."
          }))
        };

        setResultData(formattedData);
      } catch (err) {
        console.error("Failed to fetch evaluation results from backend:", err);
        setError(err?.response?.data?.message || err.message || "Failed to load results.");
      } finally {
        setLoading(false);
      }
    };

    if (sessionId) {
      fetchResult();
    }
  }, [sessionId]);

  const toggleQuestion = (id) => {
    setExpandedQuestionId(expandedQuestionId === id ? null : id);
  };

  if (loading) {
    return (
      <div className="flex h-screen flex-col items-center justify-center gap-3 text-[#4f46e5] bg-[#f8fafc]">
        <Loader2 className="w-9 h-9 animate-spin" />
        <p className="text-sm font-semibold text-slate-500">Fetching your AI score details...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center p-12 bg-[#f8fafc] min-h-screen flex flex-col items-center justify-center gap-4">
        <p className="text-red-500 font-bold text-lg">⚠️ Error: {error}</p>
        <button onClick={() => navigate(-1)} className="text-[#4f46e5] font-semibold underline text-sm">
          Go Back
        </button>
      </div>
    );
  }

  // حسابات الدائرة الخضراء للـ Score الحقيقي
  const radius = 38;
  const strokeWidth = 5;
  const circumference = radius * 2 * Math.PI;
  const strokeDashoffset = circumference - (resultData.score / 100) * circumference;

  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-800 antialiased font-sans px-4 py-8 md:px-12 w-full">
      <div className="w-full max-w-4xl mx-auto space-y-5">
        
        {/* رابط العودة للخلف */}
        <div className="flex items-center mb-2">
          <button 
            onClick={() => navigate(-1)} 
            className="flex items-center gap-1.5 text-[13px] font-semibold text-slate-400 hover:text-slate-700 transition-colors"
          >
            <ArrowLeft size={14} strokeWidth={2.5} /> Back to sessions
          </button>
        </div>

        {/* 1. السكور الحقيقي واسم الوظيفة (Card 1) */}
        <div className="bg-white border border-[#e2e8f0] rounded-[18px] p-7 shadow-[0_1px_2px_0_rgba(0,0,0,0.03)] flex items-center gap-6 w-full">
          <div className="relative flex items-center justify-center flex-shrink-0 w-20 h-20">
            <svg height="80" width="80" className="transform -rotate-90">
              <circle className="text-[#f1f5f9]" strokeWidth={strokeWidth} stroke="currentColor" fill="transparent" r={radius} cx="40" cy="40" />
              <circle className="text-[#10b981] transition-all duration-500 ease-out" strokeWidth={strokeWidth} strokeDasharray={`${circumference} ${circumference}`} style={{ strokeDashoffset }} strokeLinecap="round" stroke="currentColor" fill="transparent" r={radius} cx="40" cy="40" />
            </svg>
            <div className="absolute text-center">
              <span className="text-[24px] font-black text-slate-800 leading-none tracking-tight block">{resultData.score}</span>
              <span className="text-[10px] font-bold text-slate-400 block mt-0.5">/ 100</span>
            </div>
          </div>

          <div className="flex-1 space-y-1">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">
              INTERVIEW RESULTS
            </span>
            <h2 className="text-[22px] font-black text-slate-900 tracking-tight mb-2 capitalize">
              {resultData.jobTitle}
            </h2>
            
            <div className="flex items-center flex-wrap gap-2 text-[12px] font-bold text-slate-400">
              <span className="bg-[#e6fbf3] text-[#10b981] px-2 py-0.5 rounded-md border border-[#bbf7d0]/40 text-[11px]">
                {resultData.score}/100
              </span>
              <span className="bg-[#e6fbf3] text-[#059669] border border-[#bbf7d0]/60 px-2 py-0.5 rounded-md text-[11px] font-bold flex items-center gap-1">
                <CheckCircle2 size={12} fill="currentColor" className="text-[#10b981] stroke-white" /> {resultData.status}
              </span>
              <span className="text-slate-300 font-normal px-0.5">|</span>
              <span className="text-slate-500/80 font-semibold">{resultData.date}</span>
              <span className="text-slate-300 font-normal">•</span>
              <span className="text-slate-500/80 font-semibold">{resultData.duration}</span>
            </div>
          </div>
        </div>

        {/* 2. الـ Feedback العام والـ Tips من الباكيند (Card 2) */}
        <div className="bg-white border border-[#e2e8f0] rounded-[18px] p-7 shadow-[0_1px_2px_0_rgba(0,0,0,0.03)] w-full space-y-5">
          <h3 className="text-[15px] font-black text-[#1e293b] flex items-center gap-2 tracking-tight">
            <MessageSquare size={16} className="text-[#4f46e5]" /> Overall Feedback
          </h3>
          <p className="text-[13.5px] font-medium text-slate-600 leading-relaxed">
            {resultData.overallFeedback}
          </p>

          {resultData.tips && resultData.tips.length > 0 && (
            <div className="pt-4 border-t border-slate-100 space-y-3">
              <h4 className="text-[12.5px] font-bold text-[#b45309] flex items-center gap-1.5 uppercase tracking-wide">
                <Lightbulb size={14} className="text-[#f59e0b] fill-[#fef3c7]" /> Tips for Improvement
              </h4>
              <ul className="space-y-2.5 pl-0.5">
                {resultData.tips.map((tip, idx) => (
                  <li key={idx} className="flex items-start gap-2.5 text-[13.5px] font-medium text-slate-600 leading-relaxed">
                    <span className="w-1.5 h-1.5 bg-[#4f46e5] rounded-full mt-2 flex-shrink-0" />
                    {tip}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* 3. صندوق تفصيل الأسئلة والأجوبة والـ AI الكومنت الحقيقي (Card 3) */}
        <div className="bg-white border border-[#e2e8f0] rounded-[18px] shadow-[0_1px_2px_0_rgba(0,0,0,0.03)] overflow-hidden w-full">
          <div className="p-5 border-b border-slate-100 bg-white">
            <h3 className="text-[15px] font-black text-[#1e293b] tracking-tight">Questions Breakdown</h3>
            <p className="text-[11px] font-bold text-slate-400 mt-0.5">{resultData.questionsBreakdown.length} questions answered</p>
          </div>

          <div className="divide-y divide-[#f1f5f9]">
            {resultData.questionsBreakdown.map((q) => {
              const isExpanded = expandedQuestionId === q.id;
              return (
                <div key={q.id} className="w-full">
                  
                  {/* سطر السؤال العريض */}
                  <div 
                    onClick={() => toggleQuestion(q.id)}
                    className="p-4 flex items-center justify-between gap-4 hover:bg-[#f8fafc]/50 cursor-pointer select-none transition-colors"
                  >
                    <div className="flex items-center gap-3">
                      <span className="w-5 h-5 bg-[#eeeafe] text-[#4f46e5] font-bold text-[11px] rounded-full flex items-center justify-center flex-shrink-0">
                        {q.id}
                      </span>
                      <p className="text-[13.5px] font-bold text-slate-800 tracking-tight leading-snug">
                        {q.text}
                      </p>
                    </div>
                    
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <span className="bg-[#fef2f2] text-[#ef4444] font-bold text-[11px] px-2 py-0.5 rounded-full border border-[#fee2e2]">
                        {q.score}
                      </span>
                      {isExpanded ? <ChevronUp size={15} className="text-slate-400" /> : <ChevronDown size={15} className="text-slate-400" />}
                    </div>
                  </div>

                  {/* الجزء الممتد: يعرض إجابة اليوزر الفعلية وكومنت الـ AI عليها كلياً */}
                  {isExpanded && (
                    <div className="px-12 pb-5 pt-1 bg-[#f8fafc]/40 border-t border-[#f1f5f9] space-y-4">
                      
                      {/* صندوق إجابة اليوزر المربوط */}
                      <div className="bg-white border border-[#e2e8f0] p-4 rounded-xl shadow-sm mt-2">
                        <span className="text-[10px] font-bold text-slate-400 tracking-wider uppercase block mb-1">
                          Your Answer
                        </span>
                        <p className="text-[13px] font-medium text-slate-600 leading-relaxed">
                          {q.userAnswer}
                        </p>
                      </div>

                      {/* صندوق الـ AI Feedback المربوط بدقة */}
                      <div className="bg-[#f4f3ff] border border-[#e0e7ff] p-4 rounded-xl">
                        <span className="text-[10px] font-bold text-[#4f46e5] tracking-wider uppercase block mb-1">
                          ✨ AI Feedback Analysis
                        </span>
                        <p className="text-[13px] font-medium text-slate-700 leading-relaxed">
                          {q.aiFeedback}
                        </p>
                      </div>

                    </div>
                  )}

                </div>
              );
            })}
          </div>
        </div>

      </div>
    </div>
  );
}