import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  pdf,
} from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    backgroundColor: '#FFFFFF',
    padding: '48 56',
    fontSize: 11,
    lineHeight: 1.6,
    color: '#1E293B',
  },
  header: {
    marginBottom: 28,
    paddingBottom: 16,
    borderBottom: '1 solid #E2E8F0',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0F172A',
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 10,
    color: '#64748B',
  },
  paragraph: {
    marginBottom: 12,
    fontSize: 11,
    lineHeight: 1.65,
    color: '#334155',
  },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 56,
    right: 56,
    textAlign: 'center',
    fontSize: 8,
    color: '#94A3B8',
  },
})

const CoverLetterPdfDocument = ({ coverLetter = '', jobTitle = '', companyName = '' }) => {
  const paragraphs = coverLetter
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Cover Letter</Text>
          {(jobTitle || companyName) && (
            <Text style={styles.subtitle}>
              {[jobTitle, companyName].filter(Boolean).join(' · ')}
            </Text>
          )}
        </View>

        <View>
          {paragraphs.map((paragraph, index) => (
            <Text key={index} style={styles.paragraph}>
              {paragraph}
            </Text>
          ))}
        </View>

        <Text style={styles.footer} fixed>
          Generated by CareerForge
        </Text>
      </Page>
    </Document>
  )
}

const sanitizeFileName = (value = 'cover-letter') =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60) || 'cover-letter'

export const downloadCoverLetterPdf = async ({
  coverLetter,
  jobTitle = 'cover-letter',
  companyName = '',
}) => {
  const blob = await pdf(
    <CoverLetterPdfDocument
      coverLetter={coverLetter}
      jobTitle={jobTitle}
      companyName={companyName}
    />,
  ).toBlob()

  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${sanitizeFileName(jobTitle || companyName)}-cover-letter.pdf`
  link.click()
  URL.revokeObjectURL(url)
}

export default CoverLetterPdfDocument
