/**
 * ANALYSIS MODEL (TABLE)
 * ======================
 * 
 * PURPOSE:
 * This file defines the structure of the 'analyses' table in MongoDB.
 * It stores all CV analysis results generated by AI.
 * 
 * ASSIGNED TO: HAGER
 * 
 * COLUMNS (FIELDS) IN THIS TABLE:

 * WHAT YOU NEED TO IMPLEMENT:
 * 1. Define the schema with all fields above
 * 2. Create nested schema for matchedJobs (title + matchPercentage)
 * 3. Add index for userId to speed up queries
 * 
 * RELATED FILES:
 * - routes/analyses.js (uses this model)
 * - controllers/analysisController.js (uses this model)
 */