/**
 * ROADMAP MODEL (TABLE)
 * =====================
 * 
 * PURPOSE:
 * This file defines the structure of the 'roadmaps' table in MongoDB.
 * It stores personalized career roadmap plans generated by AI.
 * 
 * ASSIGNED TO: Ahmed
 * 
 * 
 * 
 * WHAT YOU NEED TO IMPLEMENT:
 * 1. Define the main schema with all fields above
 * 2. Create nested schema for weeklyPlan
 * 3. Add method to auto-calculate progress from completed weeks
 * 4. Add index for userId to speed up queries
 * 
 * UNIQUE FEATURE: ignoreSkills tells users what NOT to learn (time saver!)
 * 
 * RELATED FILES:
 * - routes/roadmaps.js (uses this model)
 * - controllers/roadmapController.js (uses this model)
 */